FROM node:24.16.0 AS builder

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --frozen-lockfile

COPY . .

ARG APP

RUN yarn build shared

RUN yarn build ${APP}

FROM node:24.16.0-alpine as runner

ARG APP

ENV APP=$APP

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install --prod --frozen-lockfile && yarn cache clean

COPY --from=builder app/dist/ ./dist/

CMD sh -c "node dist/apps/$APP/main"